def log(backend, user, response, *args, **kwargs):
    print('--------backend--------')
    print('========================')
    print(backend)
    print('--------user--------')
    print('========================')
    print(user)
    print('--------response--------')
    print('========================')
    print(response)
    print('--------args--------')
    print('========================')
    print(args)
    print('--------kwargs--------')
    print('========================')
    print(kwargs)