# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-16 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identity',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Basics'},
        ),
        migrations.AddField(
            model_name='identity',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='identity',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
    ]
