# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 13:14
from __future__ import unicode_literals

import danesh_boom.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=django.contrib.postgres.fields.ArrayField(base_field=danesh_boom.models.fields.PhoneField(max_length=23), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=django.contrib.postgres.fields.ArrayField(base_field=danesh_boom.models.fields.PhoneField(max_length=23), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='web_site',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=[], size=None),
        ),
    ]
