# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 21:06
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170222_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='web_site',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
    ]
