# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-16 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171216_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Basics'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Basics'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Basics'},
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Basics'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Basics'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Basics'},
        ),
        migrations.AddField(
            model_name='badge',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='badge',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='education',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='education',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='research',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='research',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='skill',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
    ]
