# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 08:31
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170226_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='from_date',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='to_date',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fax',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+\\d{1,3}-\\d{2,3}-\\d{3,14}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+\\d{1,3}-\\d{2,3}-\\d{3,14}$')]), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_code',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+\\d{1,3}-\\d{2,3}-\\d{3,14}$')]), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_account',
            field=models.CharField(blank=True, max_length=256, validators=[django.core.validators.RegexValidator('^@[\\w\\d_]+$')]),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='from_date',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='to_date',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
