# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 09:54
from __future__ import unicode_literals

import danesh_boom.models.fields
import django.contrib.postgres.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170305_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fax',
            field=danesh_boom.models.fields.PhoneField(blank=True, max_length=23),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=django.contrib.postgres.fields.ArrayField(base_field=danesh_boom.models.fields.PhoneField(max_length=23), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=django.contrib.postgres.fields.ArrayField(base_field=danesh_boom.models.fields.PhoneField(max_length=23), blank=True, null=True, size=None),
        ),
    ]
