# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20170315_1856'),
        ('users', '0005_auto_20170312_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_experience_organization', to='organizations.Organization'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='status',
            field=models.CharField(choices=[('WITHOUT_CONFIRM', 'بدون تایید'), ('WAIT_FOR_CONFIRM', 'منتظر تایید'), ('CONFIRMED', 'تایید شده'), ('UNCONFIRMED', 'تایید نشده')], default='WITHOUT_CONFIRM', max_length=20),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
