# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('users', '0008_remove_certificate_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.Media'),
        ),
    ]
