DEBUG: off
SECRET_KEY: ''
ALLOWED_HOSTS: []
DATABASE:
  ENGINE: 'django.db.backends.sqlite3'
  NAME: '../data/db.sqlite3'

EMAIL:
  ENABLE_SMTP: off
  HOST: ''
  HOST_USER: ''
  HOST_PASSWORD: ''
  PORT: 25
  USE_TLS: on
  EMAIL_FROM: ''

# relative to BASE_DIR or absolute
STATIC_ROOT: '../static'

# relative to BASE_DIR or absolute
FRONTEND_ROOT: '../danesh-boom-frontend/'

# relative to FRONTEND_ROOT or absolute
FRONTEND_BUILD_ROOT: 'build'

# use create-react-app server for static files
FRONTEND_DEV: off

SENDFILE_BACKEND: 'sendfile.backends.nginx' # Alternative 'sendfile.backends.development'
SENDFILE_ROOT: '' # e.g. '/path/to/examples/protected_downloads/protected' or '../data/protected'
SENDFILE_URL: '' # e.g. '/protected'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: '1014811326280-671ei9qe63vuk2lkkcnhovpui7vlol8t.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: '96oIE02JZewm-91ijEFr4kfY'

SOCIAL_AUTH_INSTAGRAM_KEY: '1c41576f880a4fd29c9b413b49094771'
SOCIAL_AUTH_INSTAGRAM_SECRET: '1b0fb06936f14092960b24e15f3527f7'

SOCIAL_AUTH_YAHOO_OAUTH2_KEY: 'dj0yJmk9Z3V3NE0yRFQyN2NaJmQ9WVdrOVlsQmhRMlI1TlRZbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD0wMw--'
SOCIAL_AUTH_YAHOO_OAUTH2_SECRET: '2a644ab15f39b104201fe7891c4e56dcc8527b6d'

SOCIAL_AUTH_FACEBOOK_KEY: '173378200095675'
SOCIAL_AUTH_FACEBOOK_SECRET: 'd450ea935431205042c67264d966c3a2'

SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY: '771t20xhissy4z'
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET: 'TY5sTyuzI6pz9v5v'
SOCIAL_AUTH_LINKEDIN_OAUTH2_REDIRECT_URI: 'http://localhost:8000/users/'
