DEBUG: off
SECRET_KEY: ''
ALLOWED_HOSTS: []
DATABASE:
  ENGINE: 'django.db.backends.sqlite3'
  NAME: '../data/db.sqlite3'

EMAIL:
  ENABLE_SMTP: off
  HOST: ''
  HOST_USER: ''
  HOST_PASSWORD: ''
  PORT: 25
  USE_TLS: on
  EMAIL_FROM: ''

# relative to BASE_DIR or absolute
STATIC_ROOT: '../static'

# relative to BASE_DIR or absolute
FRONTEND_ROOT: '../danesh-boom-frontend/'

# relative to FRONTEND_ROOT or absolute
FRONTEND_BUILD_ROOT: 'build'

# use create-react-app server for static files
FRONTEND_DEV: off

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: ''
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: ''

SENDFILE_BACKEND: 'sendfile.backends.nginx' # Alternative 'sendfile.backends.development'
SENDFILE_ROOT: '' # e.g. '/path/to/examples/protected_downloads/protected' or '../data/protected'
SENDFILE_URL: '' # e.g. '/protected'
