# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 14:02
from __future__ import unicode_literals

import danesh_boom.models.fields
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('nike_name', models.CharField(blank=True, max_length=100, null=True)),
                ('official_name', models.CharField(max_length=75)),
                ('national_code', models.CharField(max_length=20)),
                ('registration_ads_url', models.URLField(blank=True, null=True)),
                ('registrar_organization', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True)),
                ('phone', django.contrib.postgres.fields.ArrayField(base_field=danesh_boom.models.fields.PhoneField(max_length=23), blank=True, default=[], size=None)),
                ('web_site', models.URLField(blank=True, null=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('ownership_type', models.CharField(choices=[('idi', 'موسسه انفرادی'), ('org', 'شرکت'), ('cop', 'تعاونی'), ('pvt', 'سهامی خاص'), ('llp', 'سهامی عام'), ('gco', 'شرکت دولتی'), ('oth', 'سایر')], default='oth', max_length=20)),
                ('business_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('biography', models.TextField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('correspondence_language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[], size=None)),
                ('social_network', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=[], size=None)),
                ('staff_count', models.IntegerField(blank=True, null=True)),
                ('admins', models.ManyToManyField(blank=True, related_name='organ_admins', to=settings.AUTH_USER_MODEL)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.Media')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='organizations.Organization')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Media')),
            ],
        ),
        migrations.CreateModel(
            name='StaffCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_counts', to='organizations.Organization')),
            ],
        ),
    ]
