# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-18 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('media', '0002_auto_20171218_0717'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='follow_follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.Identity'),
        ),
        migrations.AddField(
            model_name='follow',
            name='follow_identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.Identity'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_organization', to='organizations.Organization'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Media'),
        ),
        migrations.AddField(
            model_name='customer',
            name='related_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='users.Identity'),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='confirmation_confirmed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_confirmaed', to='users.Identity'),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='confirmation_corroborant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_corroborant', to='users.Identity'),
        ),
        migrations.AddField(
            model_name='ability',
            name='ability_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='organizations.Organization'),
        ),
    ]
