# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-24 10:41
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='business_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('producer', 'تولید کننده'), ('investor', 'سرمایه گذار'), ('service provider', 'ارائه دهنده خدمات')], max_length=30), size=None),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ownership_type',
            field=models.CharField(choices=[('idi', 'موسسه انفرادی'), ('org', 'شرکت'), ('cop', 'تعاونی'), ('pvt', 'سهامی خاص'), ('llp', 'سهامی عام'), ('gco', 'شرکت دولتی'), ('oth', 'سایر')], max_length=20),
        ),
    ]
