# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20170312_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
