# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-16 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('organizations', '0003_ability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=200)),
                ('confirm_flag', models.BooleanField(default=False)),
                ('confirmed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_confirmaed', to='users.Identity')),
                ('corroborant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_corroborant', to='users.Identity')),
            ],
        ),
    ]
