# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20170318_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='logo',
        ),
    ]
