# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-16 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='customer_organization', to='organizations.Organization'),
            preserve_default=False,
        ),
    ]
