# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='picture',
        ),
    ]
