# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-16 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20171216_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Basics'},
        ),
        migrations.AlterModelOptions(
            name='confirmation',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Basics'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Basics'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Basics'},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Basics'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Basics'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Basics'},
        ),
        migrations.AlterModelOptions(
            name='staffcount',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Basics'},
        ),
        migrations.AddField(
            model_name='ability',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='ability',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='follow',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='follow',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='picture',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='picture',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staff',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staffcount',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='staffcount',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
    ]
