# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-17 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('seen_date', models.DateTimeField(blank=True)),
                ('body', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('forward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwards', to='chats.Message')),
                ('forward_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_from', to='users.Identity')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receivers', to='users.Identity')),
                ('replay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='chats.Message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sender', to='users.Identity')),
            ],
        ),
    ]
