# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-30 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('seen_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('body', models.TextField(blank=True, default=None, null=True)),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
    ]
