# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-17 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='forward',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwards', to='chats.Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='forward_from',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_from', to='users.Identity'),
        ),
        migrations.AlterField(
            model_name='message',
            name='replay',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='chats.Message'),
        ),
    ]
