# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-17 16:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20171217_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='seen_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 17, 19, 59, 25, 526657)),
        ),
    ]
