# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-17 16:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20171217_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='forward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwards', to='chats.Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='forward_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_from', to='users.Identity'),
        ),
        migrations.AlterField(
            model_name='message',
            name='replay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='chats.Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 17, 20, 0, 59, 771048)),
        ),
    ]
