# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-18 16:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20171217_1912'),
        ('chats', '0004_auto_20171217_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='forward_from',
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='media.Media'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='forward',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwards', to='chats.Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='message_receivers', to='users.Identity'),
        ),
        migrations.AlterField(
            model_name='message',
            name='replay',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='chats.Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='seen_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 18, 19, 32, 49, 646809)),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages_sender', to='users.Identity'),
        ),
    ]
