# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-18 16:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_auto_20171218_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 18, 20, 18, 21, 785079)),
        ),
    ]
