# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-19 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0019_auto_20171219_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='media.Media'),
        ),
    ]
