# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-28 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_time', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now)),
                ('delete_flag', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name_plural': 'Basics',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='BaseComment',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('text', models.TextField(help_text='Text')),
            ],
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('title', models.CharField(db_index=True, help_text='String(50)', max_length=50)),
            ],
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='HashtagParent',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('title', models.CharField(db_index=True, help_text='String(50)', max_length=50)),
            ],
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('post_type', models.CharField(choices=[('supply', 'عرضه'), ('demand', 'تقاضا'), ('post', 'پست')], default='post', help_text='supply | demand | post', max_length=10)),
                ('post_title', models.CharField(db_index=True, help_text='String(100)', max_length=100)),
                ('post_description', models.TextField(blank=True, db_index=True, help_text='String(300)', max_length=300, null=True)),
                ('post_pinned', models.BooleanField(default=False, help_text='Boolean')),
                ('post_promote', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, db_index=True, help_text='Unix Time Stamp')),
                ('post_parent', models.ForeignKey(help_text='integer', on_delete=django.db.models.deletion.CASCADE, related_name='base_posts', to='base.Base')),
            ],
            bases=('base.base',),
        ),
    ]
