# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-18 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_time', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Basics',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('related_instance_id', models.PositiveIntegerField()),
                ('created_time', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_time', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now)),
                ('c_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_mention', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='HashtagParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='hashtag',
            name='related_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_mentions', to='base.HashtagParent'),
        ),
    ]
