# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-30 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_time', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now)),
                ('delete_flag', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-pk'],
                'verbose_name_plural': 'Basics',
            },
        ),
        migrations.CreateModel(
            name='BaseComment',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('text', models.TextField(help_text='Text')),
            ],
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('title', models.CharField(db_index=True, help_text='String(50)', max_length=50)),
            ],
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='HashtagParent',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('title', models.CharField(db_index=True, help_text='String(50)', max_length=50)),
            ],
            bases=('base.base',),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='hashtag_base',
            field=models.ForeignKey(blank=True, help_text='Integer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_hashtags', to='base.Base'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='related_parent',
            field=models.ForeignKey(blank=True, help_text='String(50)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_mentions', to='base.HashtagParent'),
        ),
        migrations.AddField(
            model_name='basecomment',
            name='comment_parent',
            field=models.ForeignKey(help_text='Integer', on_delete=django.db.models.deletion.CASCADE, related_name='base_comments', to='base.Base'),
        ),
    ]
