# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-18 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20171218_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='hashtagparent',
            name='id',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='base_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hashtagparent',
            name='base_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base'),
            preserve_default=False,
        ),
    ]
