# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-18 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20171218_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_hashtags', to='base.Base'),
        ),
    ]
