# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-19 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('media', '0002_auto_20171218_0717'),
        ('base', '0004_auto_20171218_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseComment',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('comment_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_comments', to='base.Base')),
                ('comment_picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_comment_picture', to='media.Media')),
                ('comment_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_comment_senders', to='users.Identity')),
            ],
            bases=('base.base',),
        ),
    ]
