# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-19 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_basecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecomment',
            name='text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
