# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-27 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_basecomment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='delete_flag',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='basecomment',
            name='comment_parent',
            field=models.ForeignKey(help_text='Integer', on_delete=django.db.models.deletion.CASCADE, related_name='base_comments', to='base.Base'),
        ),
        migrations.AlterField(
            model_name='basecomment',
            name='comment_picture',
            field=models.ForeignKey(help_text='Integer', on_delete=django.db.models.deletion.CASCADE, related_name='base_comment_picture', to='media.Media'),
        ),
        migrations.AlterField(
            model_name='basecomment',
            name='comment_sender',
            field=models.ForeignKey(help_text='Integer', on_delete=django.db.models.deletion.CASCADE, related_name='base_comment_senders', to='users.Identity'),
        ),
        migrations.AlterField(
            model_name='basecomment',
            name='text',
            field=models.TextField(help_text='Text'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag_base',
            field=models.ForeignKey(blank=True, help_text='Integer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_hashtags', to='base.Base'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='related_parent',
            field=models.ForeignKey(blank=True, help_text='String(50)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_mentions', to='base.HashtagParent'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='title',
            field=models.CharField(db_index=True, help_text='String(50)', max_length=50),
        ),
        migrations.AlterField(
            model_name='hashtagparent',
            name='title',
            field=models.CharField(db_index=True, help_text='String(50)', max_length=50),
        ),
    ]
