# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import media.MediaStorage
import media.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=media.MediaStorage.MediaStorage(location='/home/mohsen/projects/data/protected/media'), upload_to=media.models.get_upload_path)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
