# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-30 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import media.MediaStorage
import media.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=media.MediaStorage.MediaStorage(location='/Users/saeid/Projects/danesh_boom_env/danesh-boom-backend/media'), upload_to=media.models.get_upload_path)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField(default='{}')),
            ],
        ),
    ]
