# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 14:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models

import media.MediaStorage
import media.models


class Migration(migrations.Migration):
    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(storage=media.MediaStorage.MediaStorage(location=settings.MEDIA_DIR),
                                   upload_to=media.models.get_upload_path),
        ),
    ]
