# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-23 06:14
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_basecomment_comment_sender'),
        ('users', '0001_initial'),
        ('media', '0002_auto_20171223_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('name', models.CharField(db_index=True, help_text='String(100)', max_length=100, unique=True)),
                ('title', models.CharField(db_index=True, help_text='String(100)', max_length=100)),
                ('creatable', models.BooleanField(default=False, help_text='Boolean')),
                ('category_parent', models.ForeignKey(blank=True, help_text='Integer', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='CategoryField',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('name', models.CharField(db_index=True, help_text='String(100)', max_length=100, unique=True)),
                ('title', models.CharField(db_index=True, help_text='String(100)', max_length=100)),
                ('type', models.CharField(choices=[('string', 'ارزش آن بصورت استرینگ پر شود'), ('float', 'ارزش آن بصورت عدد پر شود'), ('choices', 'ارائه ارزش بصورت انتخابی'), ('bool', 'ارئه ارزش بصورت چک باکس')], db_index=True, default='string', help_text='string | float | choices | bool', max_length=50)),
                ('order', models.IntegerField(db_index=True, default=0, help_text='Integer')),
                ('option', django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_index=True, help_text='JSON', null=True)),
                ('field_category', models.ForeignKey(help_text='Integer', on_delete=django.db.models.deletion.CASCADE, related_name='category_fields', to='products.Category')),
            ],
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('text', models.TextField(db_index=True, help_text='Text')),
            ],
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('order', models.IntegerField(default=0, help_text='Integer')),
                ('description', models.TextField(blank=True, db_index=True, help_text='Text')),
                ('picture_media', models.ForeignKey(help_text='Integer', on_delete=django.db.models.deletion.CASCADE, related_name='product_picture_media', to='media.Media')),
            ],
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('value', models.FloatField(help_text='Float')),
            ],
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('name', models.CharField(db_index=True, help_text='String(100)', max_length=100)),
                ('country', models.CharField(db_index=True, help_text='String(50)', max_length=50)),
                ('province', models.CharField(db_index=True, help_text='String(50)', max_length=50)),
                ('city', models.CharField(blank=True, db_index=True, help_text='String(50)', max_length=50)),
                ('description', models.CharField(blank=True, db_index=True, help_text='String(1000)', max_length=1000)),
                ('attrs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON', null=True)),
                ('custom_attrs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON', null=True)),
                ('product_category', models.ForeignKey(help_text='Integer', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Category')),
                ('product_owner', models.ForeignKey(help_text='Integer', on_delete=django.db.models.deletion.CASCADE, related_name='identity_products', to='users.Identity')),
            ],
            bases=('base.base',),
        ),
        migrations.AddField(
            model_name='price',
            name='price_product',
            field=models.ForeignKey(help_text='Integer', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.Product'),
        ),
        migrations.AddField(
            model_name='picture',
            name='picture_product',
            field=models.ForeignKey(help_text='Integer', on_delete=django.db.models.deletion.CASCADE, related_name='product_pictures', to='products.Product'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_product',
            field=models.ForeignKey(help_text='Integer', on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to='products.Product'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(help_text='Integer', on_delete=django.db.models.deletion.CASCADE, related_name='user_product_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
