# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-16 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Basics'},
        ),
        migrations.AlterModelOptions(
            name='categoryfield',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Basics'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Basics'},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Basics'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Basics'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Basics'},
        ),
        migrations.AddField(
            model_name='category',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='categoryfield',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='categoryfield',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='picture',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='picture',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='price',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='price',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_time',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
    ]
