# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170708_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfield',
            name='type',
            field=models.CharField(choices=[('string', 'خود شخص پر کند'), ('choices', 'انتخاب بین گزینه ها'), ('bool', 'بصورت چک باکس')], default='string', max_length=50),
        ),
    ]
