# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170711_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfield',
            name='type',
            field=models.CharField(choices=[('string', 'خود شخص  مقدار را پر کند'), ('choices', 'انتخاب مقدار بین گزینه ها'), ('bool', 'انتخاب بصورت چک باکس')], default='string', max_length=50),
        ),
    ]
