# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170711_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfield',
            name='type',
            field=models.CharField(choices=[('string', 'ارزش آن بصورت استرینگ پر شود'), ('float', 'ارزش آن بصورت عدد پر شود'), ('choices', 'ارائه ارزش بصورت انتخابی'), ('bool', 'ارئه ارزش بصورت چک باکس')], default='string', max_length=50),
        ),
    ]
